apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: sentry-exporter
  name: sentry-exporter
spec:
  ports:
    - name: "9790"
      port: 9790
      targetPort: 9790
  selector:
    io.kompose.service: sentry-exporter
status:
  loadBalancer: {}
