apiVersion: v1
data:
  ENABLE_SOCIAL_AUTH: # True or False
  GLITCHTIP_DOMAIN: # add route url create for glitchtip
kind: ConfigMap
metadata:
  annotations:
  labels:
    app.kubernetes.io/instance: glitchtip
    app.kubernetes.io/name: glitchtip
  name: glitchtip
  namespace: # add you namesspace
