apiVersion: v1
kind: DeploymentConfig
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: migrate
  name: migrate
spec:
  replicas: 1
  selector:
    io.kompose.service: migrate
  strategy:
    resources: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: migrate
    spec:
      containers:
        - args:
            - ./manage.py
            - migrate
          env:
            - name: DATABASE_URL
              value: postgres://postgres:postgres@postgres:5432/postgres
            - name: PORT
              value: "5432"
          image: ' '
          name: migrate
          resources: {}
      restartPolicy: Always
  test: false
  triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
          - migrate
        from:
          kind: ImageStreamTag
          name: migrate:latest
      type: ImageChange
status:
  availableReplicas: 0
  latestVersion: 0
  observedGeneration: 0
  replicas: 0
  unavailableReplicas: 0
  updatedReplicas: 0
