apiVersion: v1
kind: ImageStream
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: postgres
  name: postgres
spec:
  lookupPolicy:
    local: false
  tags:
    - annotations: null
      from:
        kind: DockerImage
        name: postgres:12
      generation: null
      importPolicy: {}
      name: "12"
      referencePolicy:
        type: ""
status:
  dockerImageRepository: ""
