apiVersion: v1
kind: DeploymentConfig
metadata:
  labels:
    io.kompose.service: redis
  name: redis
spec:
  replicas: 1
  selector:
    io.kompose.service: redis
  strategy:
    resources: {}
  template:
    metadata:
      labels:
        io.kompose.service: redis
    spec:
      containers:
        - image: ' '
          name: redis
          resources: 
            requests:
              cpu: 100m
              memory: 50M
            limits:
              memory: 200M
              cpu: "1"
      restartPolicy: Always
  test: false
  triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
          - redis
        from:
          kind: ImageStreamTag
          name: redis:latest
      type: ImageChange
status:
  availableReplicas: 0
  latestVersion: 0
  observedGeneration: 0
  replicas: 0
  unavailableReplicas: 0
  updatedReplicas: 0
