apiVersion: v1
kind: DeploymentConfig
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: worker
  name: worker
spec:
  replicas: 1
  selector:
    io.kompose.service: worker
  strategy:
    resources: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: worker
    spec:
      containers:
        - args:
            - celery
            - -A
            - glitchtip
            - worker
            - -B
            - -l
            - INFO
          env:
            - name: DATABASE_URL
              value: postgres://postgres:postgres@postgres:5432/postgres
            - name: DEFAULT_FROM_EMAIL
              value: no-reply@devshift.net
            - name: EMAIL_URL
              value: smtp://apikey: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@smtp.sendgrid.net:587
            - name: ENABLE_OPEN_USER_REGISTRATION
              value: "True"
            - name: GLITCHTIP_DOMAIN
              value: https://glitchtip.stage.devshift.net
            - name: PORT
              value: "8000"
            - name: SECRET_KEY
              value: postgres
            - name: GLITCHTIP_MAX_EVENT_LIFE_DAYS # As this is the retention period for teams in sentry 
              value: 30
            - name: I_PAID_FOR_GLITCHTIP
              value: "True"
            - name: ACCOUNT_LOGOUT_ON_GET
              value: "True"
            - name: LOGIN_REDIRECT_URL
              value: "home"
            - name: SITE_ID
              value: 1
          image: ' '
          name: worker
          resources: {}
      restartPolicy: Always
  test: false
  triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
          - worker
        from:
          kind: ImageStreamTag
          name: worker:latest
      type: ImageChange
status:
  availableReplicas: 0
  latestVersion: 0
  observedGeneration: 0
  replicas: 0
  unavailableReplicas: 0
  updatedReplicas: 0
