apiVersion: v1
kind: ImageStream
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: worker
  name: worker
spec:
  lookupPolicy:
    local: false
status:
  dockerImageRepository: ""
